[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  status = 200
  force = true
  from = "/authentication/*"
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/authentication/scripts/main.js"
  to = "https://mfe-authentication.netlify.app/authentication/scripts/main.js"
  status = 200
  force = true
